import Header from "../../components/Header/Header";
import Navbar from "../../components/Navbar/Navbar";

import CorporateMenphis from '../../assets/Corporate-menphis.png'

import './Home.css'

export default function Home() {

return (
    <>
        <Header/>
        <div style={{display: 'flex', width: '100vw'}}>
            <Navbar/>
            <main className="main">
                <h1 className="font-title">What is EZui?</h1>
                <img src={CorporateMenphis} alt="Placeholder Image" style={{width: "70%", borderRadius: "10px", margin: "30px auto", display: "block", boxShadow: "0 4px 40px 10px rgb(var(--primary-500-c), 0.4)"}} />
                <p className="font-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus ligula ac dui sodales maximus. Nullam tempus vestibulum efficitur. Vivamus viverra congue eleifend. Etiam consequat mi sed nulla suscipit, vitae dapibus est scelerisque. Curabitur pretium eros sed mauris cursus, eu porttitor nunc consectetur. Ut eget condimentum sem. Sed fringilla commodo lacus, ac pulvinar nulla tristique et. Maecenas tincidunt eu justo eu ullamcorper. Integer rutrum augue vitae ipsum rutrum, sit amet sodales dolor molestie. Fusce non maximus tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor dui fermentum porttitor rutrum.
                <br/>Ut eget erat sed lectus finibus accumsan. Nullam eu condimentum nibh. Aenean aliquam eu ex sed sodales. Integer vel nisl justo. Curabitur ultrices quis lacus sagittis blandit. Donec dictum, mi non lobortis tincidunt, nisl dolor rutrum mauris, non elementum nibh neque ut lectus. Nulla suscipit dui vel neque porttitor auctor. Maecenas vulputate ipsum neque, nec ullamcorper dolor iaculis nec.
                
                <br/>Nullam eget magna in velit dictum auctor. Morbi scelerisque diam non elit rhoncus, sit amet ultrices augue interdum. Pellentesque vulputate fermentum ipsum, in sagittis libero. Praesent pharetra lacus quis finibus hendrerit. Nulla gravida ullamcorper enim, fermentum eleifend massa fringilla in. Vestibulum nec neque nulla. Vestibulum nibh nibh, accumsan ac fermentum sed, euismod non metus. Nam euismod massa vel risus hendrerit, a tincidunt tortor rutrum. Nunc vestibulum sed lectus et tempus. Quisque ex neque, sagittis ac porttitor ac, eleifend vel elit. Pellentesque pulvinar sem ut egestas porta. Maecenas non massa lobortis, ultrices justo in, blandit tellus. In vel tincidunt urna. Sed condimentum ipsum nisi, ut porttitor enim tincidunt eget. Curabitur rhoncus fringilla libero. Morbi ac tristique turpis, in maximus dui.
                <br/>Morbi eget egestas nunc. Sed feugiat justo nunc, vitae luctus nunc dictum eu. Nunc felis nisi, dignissim ut ornare et, laoreet a nulla. Maecenas semper risus ac felis aliquet tincidunt. Nunc lorem metus, hendrerit a leo ac, imperdiet suscipit eros. Maecenas ac dictum est, nec imperdiet diam. Sed quis elementum ligula, eu feugiat nibh. Aenean non justo pulvinar, molestie neque nec, aliquam ipsum. Nullam ut neque leo. Proin porttitor, mauris quis accumsan gravida, est sapien varius dolor, sit amet venenatis nunc est eget sem. Aenean imperdiet iaculis commodo. Nunc quis ipsum augue. Vestibulum lobortis quis erat eu tincidunt.
                <br/>Vivamus vitae magna neque. Sed rhoncus, felis sit amet ornare molestie, eros risus aliquet leo, tempus fermentum leo mauris sit amet ipsum. Aliquam pulvinar velit vitae mi mollis suscipit. Vivamus commodo nisl vitae dignissim lobortis. Aliquam tempus tellus non sem mattis volutpat. Donec orci elit, lacinia at ullamcorper faucibus, sollicitudin sit amet justo. Nullam tincidunt nisi quis lacus posuere dictum.
                <br/>Fusce nisl ipsum, lacinia non pellentesque vel, rutrum at ligula. Pellentesque dictum mollis felis at finibus. Sed efficitur massa non leo dictum ornare. Vestibulum non leo dolor. Proin commodo nulla a erat posuere sagittis. Proin nec vehicula nulla. Duis dictum elit quis quam finibus porta. Suspendisse porttitor ultricies libero id euismod.
                <br/>Praesent sapien mauris, ullamcorper non ligula quis, pulvinar auctor purus. Donec finibus eros eget efficitur mattis. Vestibulum a mauris dui. Cras fermentum ligula et neque ornare, consequat blandit neque luctus. Aliquam a leo pharetra, ultrices tellus eu, posuere sem. Nulla quis elementum justo. Sed non lacinia metus, sed maximus magna. Aenean a sollicitudin tortor. Duis volutpat ultricies neque, sit amet molestie nisi ultricies vulputate.
                <br/>Integer tempus tincidunt quam, quis scelerisque turpis vulputate a. Mauris ac erat non ligula molestie molestie ut in urna. Suspendisse potenti. Curabitur arcu leo, dignissim non odio vel, tempus pellentesque justo. Phasellus sodales laoreet neque, vel iaculis tellus feugiat id. Vestibulum ultricies ligula ac efficitur scelerisque. Morbi lacinia, lacus ut vehicula maximus, nunc ligula mollis purus, ut hendrerit sem magna vitae justo. Aliquam ut mi quis velit porttitor mattis. Suspendisse id nulla placerat, hendrerit ante in, semper augue. Phasellus tincidunt eros at lacinia egestas. Donec tristique leo ligula, in fringilla mi bibendum non. Nulla ut vulputate est, at facilisis risus. Maecenas et tortor vel nisi finibus commodo.
                <br/>Curabitur euismod commodo orci, vitae dapibus turpis finibus vitae. Nulla hendrerit dui vel magna tincidunt, aliquam aliquet nisl euismod. Curabitur et imperdiet nunc, ut viverra est. Praesent luctus nibh quis turpis elementum semper. Donec mauris metus, molestie non ex condimentum, dictum gravida est. Sed vitae nisi et mauris ultrices mollis. Curabitur commodo magna vel sollicitudin bibendum. Maecenas luctus, tortor nec sollicitudin luctus, neque nulla semper nisl, id tempus leo nisl vitae lectus. Donec fermentum iaculis pulvinar. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
                <br/>Morbi posuere, orci non semper tincidunt, metus diam lacinia dolor, non pulvinar lectus magna in est. Ut tincidunt in metus id dignissim. Mauris placerat enim quis nulla accumsan tristique. Etiam viverra aliquet urna nec laoreet. Vestibulum ut tellus interdum, fermentum purus sit amet, feugiat felis. Donec ut magna est. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla elit nibh, mattis eget ligula ornare, mattis condimentum metus. Proin vulputate elit dolor, eget blandit dui maximus at. Mauris feugiat convallis metus non porttitor.
                <br/>Sed efficitur orci neque, non interdum velit elementum eget. Sed convallis tempus nunc, id sagittis diam cursus a. Nulla id lacus efficitur, pharetra massa et, auctor erat. Nam tincidunt interdum semper. Integer ut ante velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget dictum neque. Quisque a placerat magna. Donec fermentum rhoncus maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis luctus felis sit amet arcu congue, sed accumsan ligula venenatis. Proin arcu erat, scelerisque nec justo quis, facilisis porta velit. Aliquam erat volutpat. Quisque interdum dictum tellus a lobortis. Ut scelerisque congue odio, id congue ipsum sollicitudin id.</p>
            </main>
        </div>
    </>
)
};